modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "herbalbrews"
version = "${version}"
displayName = "Herbal Brews"
authors = "satisfy"
description = '''
New Flowers, new crafting Stations, Tea
'''
#logoFile = ""

[[dependencies.herbalbrews]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.herbalbrews]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.herbalbrews]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.herbalbrews]]
modId = "doapi"
mandatory = true
versionRange = "[1.2.8,)"
ordering = "AFTER"
side = "BOTH"
